### ISSUE TITLE
[Bug]: Replaces existing inventory on first load

### ISSUE THREAD

**Issue by dannydjdk** [Mrbysco/Initially#1]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.57

### Mod version

1.1.1

### Java version

default for MC 1.19.2

### Issue Description

When adding the mod to an existing pack/server/world and setting an item for a slot, if an item already exists in that slot for a player, Initially will replace that item, thereby voiding it. Ideally, this mod should check that the slot is empty, and either fail or find the next empty slot to place the item.

**Comment by Mrbysco** [comment]
A new version has been uploaded that fixes this issue
